apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader-uploader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: download-upload
  template:
    metadata:
      labels:
        app: download-upload
    spec:
      containers:
        - name: dl-up
          image: market-data-store:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_URL
              value: "http://api.marketstack.com/v2/eod"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: data-api-secret
                  key: api-key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_REGION
              value: "us-east-1"
            - name: S3_BUCKET_NAME
              value: "gifty-market-data"
            - name: S3_OBJECT_PREFIX
              value: "us"
            - name: TICKER
              value: "AAPL"