apiVersion: v1
kind: Service
metadata:
  name: processor-service
spec:
  type: NodePort
  selector:
    app: process-data
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30007
