apiVersion: v1
kind: Secret
metadata:
  name: data-api-secret
type: Opaque
data:
  api-key: YzkyYTcwMmMwMGZlNTk1MGI4OWViMDRkNWM2NmM5NDM=

---

apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  aws_access_key_id: QUtJQTRGRldXUUpLTzdIUVNHR00=
  aws_secret_access_key: S1hrMElQTSs3SFpkcm9Ta2FtaHNRU1FkZ21velluV1c3ajB4UmF1Ng==