apiVersion: v1
kind: Secret
metadata:
  name: data-api-secret
type: Opaque
data:
  api-key: <<>>

---

apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  aws_access_key_id: <<>>
  aws_secret_access_key: <<>>
